"""Extended tool cost table — the 49 tools that were missing from registry.py."""
from .registry import ToolCost

EXTRA_TOOL_COSTS: dict[str, ToolCost] = {
    # Visual/analysis — LLM-backed, mid/expensive
    "analyze_visual":           ToolCost(400,  1500, "mid"),
    "triage_console":           ToolCost(200,  1200, "mid"),
    "distill_hierarchy":        ToolCost(150,  800,  "mid"),
    "explain_code":             ToolCost(300,  2000, "mid"),
    "explain_function":         ToolCost(300,  2000, "mid"),
    "generate_playtest":        ToolCost(800,  2000, "expensive"),
    "run_generated_playtest":   ToolCost(800,  3000, "expensive"),
    "route_intent":             ToolCost(200,  500,  "cheap"),
    "watchdog_report":          ToolCost(100,  800,  "cheap"),
    "check_compliance":         ToolCost(100,  600,  "cheap"),
    # Pure-read probes (cheap/trivial)
    "audit_particles":          ToolCost(50,   400,  "cheap"),
    "audit_required_apis":      ToolCost(50,   400,  "cheap"),
    "block_urls":               ToolCost(50,   50,   "trivial"),
    "cdp_perf_metrics":         ToolCost(50,   300,  "trivial"),
    "clear_emulation":          ToolCost(50,   50,   "trivial"),
    "clear_network":            ToolCost(50,   50,   "trivial"),
    "click_marker":             ToolCost(100,  200,  "cheap"),
    "coverage_report":          ToolCost(100,  600,  "cheap"),
    "diagnose_text":            ToolCost(100,  400,  "cheap"),
    "discover_jake_tasks":      ToolCost(50,   400,  "trivial"),
    "find_objects_by_component": ToolCost(100,  400,  "cheap"),
    "get_animator_graph":       ToolCost(100,  500,  "cheap"),
    "get_budget_status":        ToolCost(30,   200,  "trivial"),
    "get_luna_counters":        ToolCost(50,   200,  "trivial"),
    "get_shader_variants":      ToolCost(50,   200,  "trivial"),
    "heap_sample":              ToolCost(100,  800,  "cheap"),
    "hit_test":                 ToolCost(100,  300,  "cheap"),
    "insights_events":          ToolCost(50,   400,  "cheap"),
    "insights_state":           ToolCost(50,   400,  "cheap"),
    "inspect_bodies":           ToolCost(100,  400,  "cheap"),
    "inspect_environment":      ToolCost(50,   300,  "trivial"),
    "inspect_marker":           ToolCost(100,  300,  "cheap"),
    "lifecycle_events":         ToolCost(50,   400,  "cheap"),
    "lint_csharp":              ToolCost(200,  600,  "cheap"),
    "luna_debug_discover":      ToolCost(50,   300,  "trivial"),
    "mcp_stats":                ToolCost(30,   300,  "trivial"),
    "pause_game":               ToolCost(50,   50,   "trivial"),
    "physics_query":            ToolCost(100,  400,  "cheap"),
    "resume_game":              ToolCost(50,   50,   "trivial"),
    "set_budget":               ToolCost(50,   100,  "trivial"),
    "set_cpu_throttle":         ToolCost(50,   50,   "trivial"),
    "set_device_metrics":       ToolCost(50,   50,   "trivial"),
    "set_network":              ToolCost(50,   50,   "trivial"),
    "simulate_swipe":           ToolCost(100,  100,  "cheap"),
    "trace_frames":             ToolCost(100,  600,  "cheap"),
    "tween_health":             ToolCost(50,   400,  "cheap"),
    "tween_inventory":          ToolCost(50,   400,  "cheap"),
    "wait_for_lifecycle":       ToolCost(50,   200,  "trivial"),
    "why_not_tappable":         ToolCost(100,  400,  "cheap"),
    # S6.1c — GPU/startup probes
    "get_gpu_info":             ToolCost(50,   200,  "trivial"),
    "get_vram_usage":           ToolCost(50,   300,  "trivial"),
    "get_startup_timing":       ToolCost(50,   300,  "trivial"),
    # S6.3 — playground
    "get_playground_fields":    ToolCost(50,   400,  "cheap"),
    "set_playground_field":     ToolCost(100,  100,  "cheap"),
    # S6.6 — step_frame
    "step_frame":               ToolCost(50,   50,   "trivial"),
}
